name: shared_preference
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.1+1
  fluttertoast: ^8.0.9
  lottie: ^1.3.0
  adaptive_theme: ^3.1.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0




flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/lottie/

